import { Player } from '../../core/entities/player.entity';

// Generated sample data for tests

export const players: Player[] = [
  {
    id: 'd630b1cc-efb1-45e3-9f92-ae9d2d25a1c5',
    name: 'Cristiano Ronaldo',
    age: 38,
    nationality: 'Portuguese',
    club: 'Manchester United',
    position: 'Forward',
    statistics: {
      appearances: 25,
      goals: 18,
      assists: 6,
      yellow_cards: 2,
      red_cards: 0,
      passes_completed: 320,
      passes_attempted: 380,
      pass_accuracy: 84.21,
      shots_on_target: 45,
      shot_accuracy: 60.0,
      dribbles_completed: 40,
      dribbles_attempted: 60,
      dribble_success_rate: 66.67,
      tackles_won: 15,
      interceptions: 10,
      fouls_committed: 8,
      fouls_suffered: 12,
      id: 0,
      player: undefined,
    },
  },
  {
    id: 'd630b1cc-efb1-45e3-9f92-ae9d2d25a1c6',
    name: 'Robert Lewandowski',
    age: 33,
    nationality: 'Polish',
    club: 'Bayern Munich',
    position: 'Striker',
    statistics: {
      appearances: 28,
      goals: 32,
      assists: 10,
      yellow_cards: 3,
      red_cards: 0,
      passes_completed: 280,
      passes_attempted: 320,
      pass_accuracy: 87.5,
      shots_on_target: 60,
      shot_accuracy: 70.0,
      dribbles_completed: 25,
      dribbles_attempted: 40,
      dribble_success_rate: 62.5,
      tackles_won: 10,
      interceptions: 5,
      fouls_committed: 6,
      fouls_suffered: 18,
      id: 0,
      player: undefined,
    },
  },
];

export const newPlayer = {
  name: 'Arkadiusz Szymański',
  age: 27,
  nationality: 'Polish',
  club: 'AC Milan',
  position: 'Midfielder',
  statistics: {
    appearances: 30,
    goals: 10,
    assists: 8,
    yellow_cards: 3,
    red_cards: 1,
    passes_completed: 400,
    passes_attempted: 480,
    pass_accuracy: 83.33,
    shots_on_target: 20,
    shot_accuracy: 50.0,
    dribbles_completed: 25,
    dribbles_attempted: 40,
    dribble_success_rate: 62.5,
    tackles_won: 20,
    interceptions: 15,
    fouls_committed: 10,
    fouls_suffered: 18,
  },
};
